#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034

#
#  If you use '+='' you will add new items to the existing list
#  using '=' you will replace the previous list, could be handy in a project
#  config if the global conf lists a lot of stuff normally not of interest
#  but it should be checked in a specific project
#

#
#  Use skip_plugins in a per-project config (.olint.conf) to skip one
#  or more linters. Use this as a template, and uncomment linters that
#  should not to be used
#
skip_plugins=(
    # checkbashisms
    # flake8
    # markdownlint
    # shellcheck
    # vale
)

# Explicit excludes, give entire filename as listed by olint
excludes+=(
)

# Filter by prefix, as listed by olint
prefixes+=(
    .git/
    .vscode
)

# Filter by suffix
suffixes+=(
    \~
    \#
    .pyc
)
