#!/bin/sh
#
#  Part of https://github.com/jaclu/olint
#
#  Copyright (c) 2024: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  This deploy olint and the default config file (if not already present)
#  Can be run again to deploy updates.
#

deploy_app() {
    f_destination="$(echo "$CURRENT_DIR/.destination" | sed 's#^\./##')"

    echo
    if [ ! -f "$f_destination" ]; then
        echo "If you put a destination folder in the file $f_destination"
        echo "This deploy will use rsync and install/update olint to that location."
        echo "This would typically only need sudo on first deploy."
        echo "Example:"
        echo "  echo /usr/local/bin > $f_destination"
        exit 1
    fi

    dest="$(cat "$f_destination")"

    if [ ! -d "$dest" ]; then
        echo
        echo "ERROR: The directory mentioned in .destination does not exist"
        echo "       Supplied destination: $dest"
        exit 1
    fi

    rsync -ahP --inplace "$CURRENT_DIR"/olint "$dest" | grep -v -e '^./$' -e '^sending incremental'
}

deploy_default_config() {
    d_default_conf="$("$CURRENT_DIR"/olint -C)"
    f_default_conf="$d_default_conf/config"
    if [ -f "$f_default_conf" ]; then
        echo "Global config already pressent: $f_default_conf"
    else
        cp "$CURRENT_DIR"/default_config "$f_default_conf"

        echo
        echo "A default config has been copied to $f_default_conf"
        echo "You should inspect it to ensure it matches your preferences."
        echo "As long as it is present, it will not be overwritten."

    fi
}

#===============================================================
#
#   Main
#
#===============================================================

CURRENT_DIR="$(dirname -- "$0")"

echo
echo "-----   Deploying olint   -----"

deploy_default_config
deploy_app
