#!/usr/bin/env bash
#  This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  pip install ansible-lint  # fails on ish & termux
#  brew install ansible-lint
#  (Ubuntu) sudo apt install ansible-lint
#  (Alpine) sudo apk add ansible-lint
#        crashes on iSH as of 25-04-19

# project config files: .ansible-lint.yml
#  ---
#  rules:
#    skip:
#      - ANSIBLE0012

plugin_cmd=ansible-lint
proj_plugin_cmd=ansible-lint

# Slow and comprehensive; belongs in the deep-analysis tier
plugin_priority=15

# file extensions this plugin handles
plugin_extensions=(
    .yml
    .yaml
)

# file-types this plugin handles
#plugin_file_types=(
#)

# Files this plugin should not handle
#plugin_excludes=(
#    ./tmp/foo.sh
#)
