#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Installation methods;
#  pip install bandit
#  brew install bandit
#  (Ubunu) apt install bandit

plugin_cmd="bandit"  # -q"

plugin_priority=50

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
