#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables
#
# Super simple and quick script tesster, will print out basic errors detected
# so can be used if shellcheck is unavailable.
#

if [[ -n "$(command -v shellcheck)" ]]; then
    plugin_cmd="/dev/null"
else
    plugin_cmd="bash --norc -n"
fi

# file extensions this plugin handles
plugin_extensions=(
    .sh
    .bash
)

# file-types this plugin handles
plugin_file_types=(
    "POSIX shell script*"
    "Bourne-Again shell script*"
)

plugin_priority=95
