#!/usr/bin/env bash
#  This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  pip3 install bashate  # usable on iSH
#  brew install bashate
#  (Ubuntu) sudo apt install python3-bashate

# bashate doesn't have a config file, so I created one!
# and included bashate-wrapper. This is called by olint to first parse
# this config then run bashate
# project config file: .bashateconfig
#  max-line-length=92
#  ignore=E001,E002

# remember to set the same in bashate-wrapper!!
plugin_cmd="bashate -eE005,E042,E043 -iE011"

if command -v bashate-wrapper >/dev/null; then
    # TODO: check of the shfmt conditions should be put in bashate-wrapper
    # this reads .bashateconfig
    plugin_cmd="bashate-wrapper"
elif command -v shfmt >/dev/null; then
    # In this case shfmt does the heavy lifting and bashate is only used
    # for residual policy checks
    plugin_cmd="$plugin_cmd --ignore=E003,E006,E010,E011,E020"
fi

# much faster than shellcheck, but in a few corner cases will fail to
# give a meaningful error. such as missing a } somewhere will just
# be reported as unexpected end of file.
# so better to run after shellcheck
plugin_priority=40

#  file-types this plugin handles
plugin_file_types=(
    "Bourne-Again shell script*"
    "Paul Falstad's zsh script*"

    "a /sbin/openrc-run script*"
    "OpenRC script"
)

plugin_extensions=(
    .bash
)
