#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Super simple and quick script tesster, will print out basic errors detected
#  so can be used if shellcheck is unavailable.
# Strengths:
# Use case:
# Caveats: Only checks if script can run at all

if command -v shellcheck >/dev/null; then
    plugin_cmd=/dev/null
else
    plugin_cmd="bash --norc -n"
fi

# Extremely fast but only checks for basic syntax issues
plugin_priority=211

# file extensions this plugin handles
plugin_extensions=(
    .sh
    .bash
)

# file-types this plugin handles
plugin_file_types=(
    "POSIX shell script*"
    "Bourne-Again shell script*"
)
