#!/bin/bash
#  This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  pip3 install bashate  # usable on iSH
#  brew install bashate
#  (Ubuntu) sudo apt install python3-bashate

# inline-excludes:  # noqa: E001
# project config files: .bashateconfig
#  max-line-length=92
#  ignore=E001,E002

plugin_cmd="bashate"

if command -v "$plugin_cmd" >/dev/null; then
    if command -v bashate-wrapper >/dev/null; then
        # this reads .bashateconfig
        plugin_cmd="bashate-wrapper"
    fi
fi

plugin_priority=60

#  file-types this plugin handles
plugin_file_types=(
    "Bourne-Again shell script*"
)

plugin_extensions=(
    .bash
)
