#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Purpose:
#  Code formatter.
# Strengths:
#  Enforces consistent formatting across your codebase.
# Use case:
#  Works well alongside linters like Flake8 and Pylint for a unified style.

# Installation methods;
#  pip install black
#  brew install black
#  (Ubuntu) sudo apt install black
#  (Alpine) sudo apk add black

plugin_cmd="black"

plugin_priority=60

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
