#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Code formatter. - Be aware: Modifies the code!
# Strengths:
#  Enforces consistent formatting across your codebase.
# Use case:
#  Works well alongside linters like Flake8 and Pylint for a unified style.
# Redundant if ruff is found

# Installation methods;
#  pip install black  # usable on iSH
#  brew install black
#  (Ubuntu) sudo apt install black
#  (Alpine) sudo apk add black

# inline-excludes:  # fmt: skip
# line above a block: # fmt: off
# line after a blick: # fmt: on
# project config files: pyproject.toml $XDG_CONFIG_HOME/black (~/.config/ if not set)
#  [tool.black]

plugin_cmd="black"
proj_plugin_cmd="black ."

plugin_priority=96

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)

# Handle entire project, sample pyproject.toml block:
#
# [tool.black]
# line-length = 92
# exclude = '''
# /(
#     \.venv    # Match .venv directory
# )/
# '''
