#!/bin/bash
#  This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034  # dont warn about unused variables

# plugin_cmd="checkbashisms -n -x "
plugin_cmd=do_checkbashisms # never trigger error, just display issues

#
#  if defined, check this for pressence, instead of plugin_cmd
#  useful if a function is used, since then pressence of the function
#  would give a false positive
#
plugin_cmd_actual="checkbashisms"

plugin_priority=5 #  suggested order when multiple plugins can handle a file

#  file-types this plugin handles
plugin_file_types=(
    "POSIX shell script*"
)

#
#  Instead of aborting on error, just display output to /dev/stderr
#  and always return true
#
do_checkbashisms() {
    local fname="$1"
    $plugin_cmd_actual -n -x "$fname" || echo >/dev/stderr
    true # override potential error
}
