#!/bin/bash
# shellcheck disable=SC2034

plugin_name="checkbashisms"

# plugin_cmd="checkbashisms -n -x "
plugin_cmd=do_checkbashisms # never trigger error, just display issues
plugin_priority=5           # suggested order when multiple plugins can handle a file

# file extensions this plugin handles
plugin_extensions=(
    .sh
)

# file-types this plugin handles
plugin_file_types=(
    "POSIX shell script*"
)

#
#  Instead of aborting on error, just display output to /dev/stderr
#  and always return true
#
do_checkbashisms() {
    local fname="$1"
    dbg_print "get_config() XXXXX"
    checkbashisms -n -x "$fname" || echo >/dev/stderr
    true # override potential error
}
