#!/usr/bin/env bash
#  This is sourced. Fake bang-path to help editors and linters
#  shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  pip install codespell  # usable on iSH
#  brew install codespell
#  (Ubuntu) sudo apt install codespell
#  (Alpine) sudo apk add py3-codespell

# if there are terms that should be accepted
# override_linter_cmd["codespell"]="codespell -L THIS"
#
# If there are files that should not be linted by codespell, add this
# override_linter_cmd["codespell"]="codespell -S file1,file2"

# This is not really meaningful to run on a per file basis, since
# there isn't any file type associated, so in the clobal config this
# is set as a project linter.

# plugin_cmd="codespell"

proj_plugin_cmd="codespell -H -S './.git,./.venv,./.mypy_cache'"

# extremely fast tool, so might as well run early
plugin_priority=95
