#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables
#
# Flake8 also provides: PyFlakes, pycodestyle, McCabe
# so it would be redundant to also run them if you use Flake8
#

# Dependencies:
# Alpine: available via apk py3-flake8

plugin_cmd="flake8 --color=always"

plugin_priority=60

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
