#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

plugin_cmd="flake8 --color=always"
plugin_priority=20 # suggested order when multiple plugins can handle a file

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
