#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Checks and formats import statements. - Be aware: Modifies the code!
# Strengths:
#  Ensures imports are grouped and ordered correctly according to PEP 8.
# Use case:
#  Keeps imports organized and clean.
# Caveats:
#  Only used if isort_allow_usage=1, since it disagrees with ruff check in many cases

# Installation methods;
#  pip install isort  # usable on iSH
#  brew install isort
#  (Ubuntu) sudo apt install isort
#  (Alpine) sudo apk add py3-isort

plugin_priority=115

# isort_allow_usage is supplied via config when applicable.
# shellcheck disable=SC2154
if [[ "$isort_allow_usage" = 1 ]]; then
    plugin_cmd="isort"
    proj_plugin_cmd="isort --gitignore ."
else
    plugin_cmd=/dev/null
    proj_plugin_cmd=/dev/null
fi

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
