#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Purpose:
#  Checks and formats import statements.
# Strengths:
#  Ensures imports are grouped and ordered correctly according to PEP 8.
# Use case:
#  Keeps imports organized and clean.

# Installation methods;
#  pip install isort
#  brew install isort
#  (Ubuntu) sudo apt install isort
#  (Alpine) sudo apk add py3-isort

plugin_cmd="isort"

plugin_priority=90


# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
