#!/bin/bash
# shellcheck disable=SC2034

plugin_name="jsonlint"
plugin_cmd="jsonlint -p"
plugin_priority=5 # suggested order when multiple plugins can handle a file

# file extensions this plugin handles
plugin_extensions=(
    .json
)

# file-types this plugin handles
plugin_file_types=(
    "JSON data"
)
