#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# This linter ignores Ctrl-C and I havent figured out how to solve this...

plugin_name="jsonlint"
plugin_cmd="jsonlint -p"
plugin_priority=10 # suggested order when multiple plugins can handle a file

# file extensions this plugin handles
plugin_extensions=(
    .json
)

# file-types this plugin handles
plugin_file_types=(
    "JSON data"
)
