#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Installation methods;
#  pip install mypy
#  brew install mypy
#  (Ubuntu) sudo apt install mypy
#  (Alpine) sudo apk add py3-mypy

plugin_cmd="mypy"

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
