#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose: style issues not fixed by black (formerly called pep8)
# Strengths:
# Use case:
# Caveats: Skipped if ruff or flake8 is found

# Installation methods;
#  pip install pycodestyle  # usable on iSH
#  brew install pycodestyle
#  (Ubuntu) sudo apt install pycodestyle
#  (Alpine) sudo apk add py3-pycodestyle

# inline-excludes:  # noqa: E402
# project config files: setup.cfg
#  [pycodestyle]
#  max-line-length = 92

if [[ -n "$(command -v ruff)" ]] || [[ -n "$(command -v flake8)" ]]; then
    #
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    plugin_cmd="/dev/null"
    proj_plugin_cmd="/dev/null"
else
    plugin_cmd="pycodestyle"
    proj_plugin_cmd="pycodestyle --exclude=.venv ."
fi

plugin_priority=75

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
