#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

#
# Provided by flake8, dont use this if flake8 is used!
#

# Installation methods;
#  pip install pycodestyle
#  brew install pycodestyle
#  (Ubuntu) apt install pycodestyle
#  (Alpine) apk add py3-pycodestyle

if [[ -n "$(command -v flake8)" ]]; then
    #
    # redundant if flake8 is found (and used)
    # pycodestyle is part of flake8
    #
    plugin_cmd="/dev/null"
else
    plugin_cmd="pycodestyle"
fi

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
