#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

#
# Provided by flake8, dont use this if flake8 is used!
#

# Installation methods;
#  pip install pyflakes

#  (Ubuntu) sudo apt install pyflakes3
#  (Alpine) sudo apk add py3-pyflakes

if [[ -n "$(command -v flake8)" ]]; then
    #
    # Redundant if flake8 is found, this is part of flake8
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    plugin_cmd="/dev/null"
else
    if [[ -n "$(command -v pyflakes3)" ]]; then
	plugin_cmd="pyflakes3"
    else
	plugin_cmd="pyflakes"
    fi		
fi

plugin_priority=60

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
