#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Purpose:
#  General-purpose linter for Python code quality and style.
# Strengths:
#  Provides detailed and strict checks.
#  Customizable via a .pylintrc configuration file.
# Use case:
#  Detects potential bugs, enforces coding standards, and warns about unused
#  imports or variables.

# Installation methods;
#  pip install pylint
#  brew install pylint
#  (Ubuntu) sudo apt install pylint
#  (Alpine) sudo apk add py3-pylint

plugin_cmd="pylint"

plugin_priority=90

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
