#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# python markdown linter, could be used when brew can not provide markdownlint-cli2
# drawback, typically has to be installed in a venv

# Installation methods;
#  pip install pymarkdownlnt - Do NOT install pymarkdown pkg!

# project config files:

# pyproject.toml
# [tool.pymarkdown]
# plugins.MD013.enabled = true
# plugins.MD013.line_length = 92

# Or the more readable form:

# plugins.line-length.enabled = true
# plugins.line-length.line_length = 92

# .pymarkdown.yaml:
# ---
# plugins:
#   MD013:
#     enabled: true
#     line_length: 92

# .pymarkdown (JSON5)
# {
#     "plugins": {
#         "MD013": {
#             "enabled": true,
#             "line_length": 92
#         }
#     }
# }

plugin_cmd="pymarkdown scan"
proj_plugin_cmd="pymarkdown scan -r ."
plugin_priority=70

# file extensions this plugin handles
plugin_extensions=(
    .md
)
