#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# python markdown linter, could be used when brew is not available
# drawback, typically has to be installed in a venv

# Installation methods;
#  pip install pymarkdownlnt

# project config file: pyproject.toml
#
# Config samples:
#
# [tool.pymarkdown.plugins.md013]
# line_length = 92

# [tool.pymarkdown]
# plugins.md033.allowed_elements = "nbsp"

# [tool.pymarkdown.plugins.md024]
# enabled = false

pugin_cmd="pymarkdown scan"
proj_plugin_cmd="pymarkdown scan -r ."

# file extensions this plugin handles
plugin_extensions=(
    .md
)
