#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Alternative python markdownlinter, could be used when brew is not available
# drawback, typically has to be installed in a venv

# Installation methods;
#  pip install pymarkdownlnt

plugin_cmd="pymarkdownlnt scan"
# If used on the whole project
# proj_plugin_cmd="pymarkdownlnt scan -r ."

# file extensions this plugin handles
plugin_extensions=(
    .md
)
