#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Static type checking
# Strengths:
#  Overlaps with mypy but is less strict, making it more suitable for
#  gradual adoption of type hints.
#  Be aware: For CLI pyright makes sense, in vscode Pylance should be used,
#  since it uses the pyright engine but offers better integration
# Use case:
#  Provides type checks and basic linting as you write code.
# Redundant if mypy is found

# Installation methods;
#  pip install pyright  # iSH can install but fails to run this
#  brew install pyright
#  npm install -g pyright

# line above: # pyright: reportGeneralTypeIssues=false
# line above: # pyright: reportMissingImports=false
# project config file: pyrightconfig.json
# {
#     "exclude": [
#         ".venv",
#     ],
# }

# Don't use if mypy is present
if [[ -n "$(command -v mypy)" ]]; then
    #
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    plugin_cmd="/dev/null"
    proj_plugin_cmd="/dev/null"
else
    # avoiding parallelism is normally not a performance bottle neck
    # and avoids flake8 to fail on limited systems
    plugin_cmd="pyright"
    proj_plugin_cmd="pyright ."
fi

plugin_priority=35

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
