#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Purpose:
#  Static type checking and linting (by Microsoft).
# Strengths:
#  Overlaps with Mypy but is less strict, making it more suitable for
#  gradual adoption of type hints.
#  Be aware: For CLI pyright makes sense, in vscode Pylance should be used,
#  since it uses the pyright enginge but offers better integration
# Use case:
#  Provides type checks and basic linting as you write code.

# Installation methods;
#  pip install pyright
#  brew install pyright

plugin_cmd="pyright"

plugin_priority=85

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
