#!/bin/bash
# shellcheck disable=SC2034

# This linter ignores Ctrl-C and I havent figured out how to solve this...

plugin_cmd="rslint"

# file extensions this plugin handles
plugin_extensions=(
    .js
    .ts
)

# file-types this plugin handles
plugin_file_types=(
)
