#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Extremely fast Python linter, written in Rust
# Strengths:
#  Ruff can be used to replace Flake8 (plus dozens of plugins), Black, isort,
#  pydocstyle, pyupgrade, autoflake, and more, all while executing tens or
#  hundreds of times faster than any individual tool.
# Use case:
#  Rapid linting

# Installation methods;
#  pip install ruff  # dependency: rust  iSH can install but fails to run this
#  brew install ruff
#  (Alpine) sudo apk add ruff # segfaults on iSH

# inline-excludes:  # noqa: F403,F401

if [[ -n "$(command -v black)" ]]; then
    # If black is present, let it handle formating
    # If ruff should do formating irregardless if black is
    # present, remove this condition
    #
    # set to /dev/null instead of "" to avoid warning
    #   missing: plugin_cmd
    #
    plugin_cmd="/dev/null"
    proj_plugin_cmd="/dev/null"
else
    plugin_cmd="ruff format"
    proj_plugin_cmd="ruff format"
fi

# run as one of the last steps
plugin_priority=97

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
