#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Extremely fast Python linter, written in Rust, this instance checks code
#  if ruff_change_code=1 then it auto-fixes issues
# Strengths:
#  Ruff can be used to replace Flake8 (plus dozens of plugins), Black, isort,
#  pydocstyle, pyupgrade, autoflake, and more, all while executing tens or
#  hundreds of times faster than any individual tool.
# Use case:
#  Rapid linting

# Installation methods;
#  pip install ruff  # dependency: rust  iSH can install but fails to run this
#  brew install ruff
#  (Alpine) sudo apk add ruff # segfaults on iSH
#  (Termux) apt install ruff

# Sample config (pyproject.toml)
# F & BLE must be present to ensure ruff linting doesn't leave issues
# pylint would reject on nodes not using ruff
#
# [tool.ruff.lint]
# select = ["E", "W", "I", "UP", "F", "BLE"]

# inline-excludes:  # noqa: F403,F401

# should be in global settings, this just to avoid lint issues
ruff_change_code="${ruff_change_code:-0}"

# if --fix is used use priority 95, to indicate this changes code, otherwise 85
if [[ "$ruff_change_code" -eq 1 ]]; then
    plugin_cmd="ruff check --fix"
    proj_plugin_cmd="ruff check --fix ."
    plugin_priority=120
else
    plugin_cmd="ruff check"
    proj_plugin_cmd="ruff check ."
    plugin_priority=90
fi

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
