#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Extremely fast Python linter, written in Rust, this instance only handles formatting
# Strengths:
#  Ruff can be used to replace Flake8 (plus dozens of plugins), Black, isort,
#  pydocstyle, pyupgrade, autoflake, and more, all while executing tens or
#  hundreds of times faster than any individual tool.
# Use case:
#  Rapid linting
# Caveats:
#  black_allow_usage=1 and black found disables this

# Installation methods;
# Not usable on iSH - segfaults - last checked: 26-08-18
#  pip install ruff  # dependency: rust  iSH can install but fails to run
#  brew install ruff
#  (Alpine) sudo apk add ruff # segfaults on iSH

# Sample config (pyproject.toml)
# F & BLE must be present to ensure ruff linting doesn't leave issues
# pylint would reject on nodes not using ruff
#
# [tool.ruff.lint]
# select = ["E", "W", "I", "UP", "F", "BLE"]

# inline-excludes:  # noqa: F403,F401

plugin_priority=110

# black_allow_usage is supplied via config when applicable.
# shellcheck disable=SC2154
if [[ "$black_allow_usage" = 1 ]] && command -v black >/dev/null; then
    plugin_cmd=/dev/null
    proj_plugin_cmd=/dev/null
else
    plugin_cmd="ruff format"
    proj_plugin_cmd="ruff format"
fi

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
