#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Installation methods;
#  pip install ryff
#  brew install ruff
#  (Alpine) sudo apk add ruff

plugin_cmd="ruff check"

# really fast so run early
plugin_priority=96

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)
