#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Purpose:
#  Extremely fast Python linter, written in Rust, this instance checks code
#  if ruff_change_code=1 then it auto-fixes issues
# Strengths:
#  Ruff can be used to replace Flake8 (plus dozens of plugins), Black, isort,
#  pydocstyle, pyupgrade, autoflake, and more, all while executing tens or
#  hundreds of times faster than any individual tool.
# Use case:
#  Rapid linting
# Caveats:
#  isort_allow_usage=1 and isort found and ruff using I001 disables this

# Installation methods;
# Not usable on iSH - segfaults - last checked: 26-08-18
#  pip install ruff  # dependency: rust  iSH can install but fails to run
#  brew install ruff
#  (Alpine) sudo apk add ruff # segfaults on iSH
#  (Termux) apt install ruff

# Sample config (pyproject.toml)
# F & BLE must be present to ensure ruff linting doesn't leave issues
# pylint would reject on nodes not using ruff
#
# [tool.ruff.lint]
# select = ["E", "W", "I", "UP", "F", "BLE"]

# inline-excludes:  # noqa: F403,F401

# file extensions this plugin handles
plugin_extensions=(
    .py
    .py3
)

# file-types this plugin handles
plugin_file_types=(
    "Python script*"
)

# ruff_change_code is supplied via config when applicable.
# shellcheck disable=SC2154
if [[ "$ruff_change_code" = 1 ]]; then
    plugin_cmd="ruff check --fix"
    proj_plugin_cmd="ruff check --fix ."
    plugin_priority=120
else
    plugin_cmd="ruff check"
    proj_plugin_cmd="ruff check ."
    plugin_priority=90
fi

# isort_allow_usage is supplied via config when applicable.
# shellcheck disable=SC2154
if [[ "$isort_allow_usage" = 1 ]]; then
    if [[ -n "$(command -v isort)" ]]; then
        case "$(ruff check --show-settings 2>/dev/null)" in
            *I001*)
                # ruff import order might conflict with isort
                plugin_cmd="/dev/null"
                proj_plugin_cmd="/dev/null"
                ;;
            *) ;;
        esac
    fi
fi
