#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # dont warn about unused variables

# Installation methods;
#  pip install shellcheck-py
#  brew install shellcheck
#  (Ubuntu) sudo apt install shellcheck
#  (Alpine edge) sudo apk add shellcheck

# line above:  # shellcheck disable=SC2059
# line above:  # shellcheck source=/dev/null
# project config files: .shellcheckrc
# -o all -e SC2250,SC2312
# is the same as creating a .shellcheckrc in a project dir with:
#  enable=all
#  disable=SC2250,SC2312

plugin_cmd="shellcheck -a -x --color=always -o all -e SC2250,SC2312"

# file extensions this plugin handles
plugin_extensions=(
    .sh
    .bash
)

# file-types this plugin handles
plugin_file_types=(
    "POSIX shell script*"
    "Bourne-Again shell script*"
)

# Files this plugin should not handle
#plugin_excludes=(
#    ./tmp/foo.sh
#)
