#!/usr/bin/env bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Installation methods;
#  brew install shfmt
#  go install mvdan.cc/sh/v3/cmd/shfmt@latest
#  (Ubuntu) sudo apt install shfmt
#  (Alpine edge) sudo apk add shfmt
#

plugin_cmd="shfmt -i 4 -ci -bn -w"

plugin_priority=70

# file extensions this plugin handles
plugin_extensions=(
    .sh
    .bash
)

# file-types this plugin handles
plugin_file_types=(
    "POSIX shell script*"
    "Bourne-Again shell script*"
)
