#!/bin/bash
# shellcheck disable=SC2034

plugin_cmd="yamllint -s" # never trigger error, just display issues

# file extensions this plugin handles
plugin_extensions=(
    .yml
)

# file-types this plugin handles
plugin_file_types=(
)
